const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let candidates=[],decisions=new Map(),pendingDecision=null;
const queue=document.getElementById('reviewQueue'),notice=document.getElementById('reviewNotice'),stats=document.getElementById('reviewStats'),search=document.getElementById('reviewSearch'),filter=document.getElementById('reviewFilter');
const workflowUrl='https://github.com/Triyan31/Triyan31.github.io/actions/workflows/academic-review-decision.yml';
const doiNorm=v=>String(v||'').trim().toLowerCase().replace(/^https?:\/\/doi\.org\//,'').replace(/^doi:/,'').trim();
const doiUrl=doi=>doi?`https://doi.org/${encodeURIComponent(doiNorm(doi))}`:'';
function decisionFor(c){return decisions.get(doiNorm(c.doi))||null;}
function stateFor(c){const d=decisionFor(c);if(d?.decision==='approve')return'verified';if(d?.decision==='reject')return'rejected';return'needs_review';}
function confidence(c){const s=Number(c.author_similarity||0);if(c.identity_name_match&&s>=.9)return['HIGHER','higher'];if(c.identity_name_match&&s>=.78)return['AMBIGUOUS','ambiguous'];return['WEAK','weak'];}
function renderStats(report){const s=report.verification_summary||{},verified=candidates.filter(c=>stateFor(c)==='verified').length,rejected=candidates.filter(c=>stateFor(c)==='rejected').length,pending=candidates.filter(c=>stateFor(c)==='needs_review').length;stats.innerHTML=`<article><strong>${s.total_public_records||0}</strong><span>Public records checked</span></article><article><strong>${verified}</strong><span>Confirmed mine</span></article><article><strong>${rejected}</strong><span>Not mine</span></article><article><strong>${pending}</strong><span>Needs review</span></article><article><strong>${candidates.length}</strong><span>Discovery candidates</span></article>`;}
function decisionControls(c){const doi=c.doi||'',state=stateFor(c),d=decisionFor(c);if(!doi)return`<span class="review-decision-note">No DOI: keep for manual review.</span>`;if(state!=='needs_review'){const approved=state==='verified',when=d?.decided_at?new Date(d.decided_at).toLocaleString():'';return`<div class="decision-panel decision-recorded"><span class="decision-state ${approved?'approved':'rejected'}">${approved?'✓ Confirmed mine':'✕ Not mine'}</span><span class="review-decision-note">Recorded by authenticated workflow${when?` · ${escapeHtml(when)}`:''}. This persisted decision is loaded from the repository audit record.</span></div>`;}return`<div class="decision-panel" data-doi="${escapeHtml(doi)}"><button class="btn decision approve" type="button" data-decision="approve" data-doi="${escapeHtml(doi)}">✓ Confirm mine</button><button class="btn decision reject" type="button" data-decision="reject" data-doi="${escapeHtml(doi)}">✕ Not mine</button><button class="btn decision pending" type="button" data-decision="pending" data-doi="${escapeHtml(doi)}">? Keep for review</button><span class="review-decision-note">Approve/reject is completed through authenticated GitHub Actions. Approval remains fail-closed until identity and bibliographic checks pass.</span></div>`;}
function card(c,i){const[label,cls]=confidence(c),authors=(c.authors||[]).join(' · '),url=doiUrl(c.doi),score=c.author_similarity?`${Math.round(c.author_similarity*100)}%`:'—',state=stateFor(c);return`<article class="review-card" data-match="${c.identity_name_match?'strong':'weak'}" data-state="${state}"><div class="review-card-index">${String(i+1).padStart(2,'0')}</div><div class="review-card-main"><div class="review-card-meta"><span>${escapeHtml(c.year||'YEAR ?')}</span><span>${escapeHtml(c.venue||c.publisher||'Source metadata')}</span><span class="confidence ${cls}">${label}</span><span class="confidence ${state==='verified'?'higher':state==='rejected'?'weak':'ambiguous'}">${state==='verified'?'VERIFIED':state==='rejected'?'REJECTED':'NEEDS REVIEW'}</span></div><h3>${url?`<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(c.title||'Untitled candidate')} ↗</a>`:escapeHtml(c.title||'Untitled candidate')}</h3><p class="candidate-authors">${escapeHtml(authors||'Authors unavailable')}</p><div class="evidence-grid"><div><span>DOI</span><strong>${escapeHtml(c.doi||'—')}</strong></div><div><span>Name similarity</span><strong>${score}</strong></div><div><span>Matched author</span><strong>${escapeHtml(c.matched_author||'No confident match')}</strong></div><div><span>Discovery source</span><strong>${escapeHtml(c.source||'—')}</strong></div></div><p class="review-reason">${escapeHtml(c.reason||'')}</p><div class="review-actions">${url?`<a class="btn primary" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">Open DOI / source ↗</a>`:''}<a class="btn ghost" href="https://github.com/Triyan31/Triyan31.github.io/blob/main/data/academic-review.json" target="_blank" rel="noreferrer">Inspect evidence JSON ↗</a></div>${decisionControls(c)}</div></article>`;}
function render(){const term=(search.value||'').toLowerCase().trim(),mode=filter.value;const visible=candidates.filter(c=>{const hay=[c.title,c.doi,c.venue,c.publisher,...(c.authors||[])].join(' ').toLowerCase(),state=stateFor(c);let ok=true;if(mode==='strong')ok=!!c.identity_name_match;else if(mode==='weak')ok=!c.identity_name_match;else if(['needs_review','verified','rejected'].includes(mode))ok=state===mode;return ok&&(!term||hay.includes(term));});queue.innerHTML=visible.length?visible.map(card).join(''):`<div class="review-empty">No candidates match this view.</div>`;notice.textContent=`${visible.length} of ${candidates.length} candidates shown. Decisions are persisted in the repository; a name match alone is never proof of authorship.`;}
function candidateByDoi(doi){return candidates.find(c=>doiNorm(c.doi)===doiNorm(doi))||{};}
function closeDecisionDialog(){document.querySelector('.decision-confirm-overlay')?.remove();pendingDecision=null;}
function openDecisionDialog(doi,action){const c=candidateByDoi(doi);pendingDecision={doi,action};const approving=action==='approve',label=approving?'Confirm as my article':'Mark as not mine',explanation=approving?'This does not publish the article immediately. The authenticated workflow will still require identity and bibliographic checks to pass.':'This will submit an authenticated decision that this candidate is not your article.';document.body.insertAdjacentHTML('beforeend',`<div class="decision-confirm-overlay" role="presentation"><section class="decision-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="decisionDialogTitle"><span class="decision-dialog-kicker">ACADEMIC REVIEW · CONFIRM DECISION</span><h2 id="decisionDialogTitle">${escapeHtml(label)}</h2><div class="decision-dialog-record"><span>Article</span><strong>${escapeHtml(c.title||'Untitled candidate')}</strong><span>DOI</span><code>${escapeHtml(doi)}</code></div><p>${escapeHtml(explanation)}</p><div class="decision-dialog-security"><strong>Authenticated step required</strong><span>GitHub Actions remains the trusted execution layer. After the workflow succeeds, this page will read the persisted decision on its next refresh.</span></div><div class="decision-dialog-actions"><button class="btn ghost" type="button" data-dialog-cancel>Cancel</button><button class="btn ${approving?'decision approve':'decision reject'}" type="button" data-dialog-continue>${approving?'Continue: confirm mine':'Continue: not mine'} →</button></div></section></div>`);document.querySelector('[data-dialog-continue]')?.focus();}
async function continueDecision(){if(!pendingDecision)return;const{doi,action}=pendingDecision;try{await navigator.clipboard.writeText(`action=${action}\ndoi=${doi}`);}catch(_){}closeDecisionDialog();window.open(workflowUrl,'_blank','noopener,noreferrer');}
queue.addEventListener('click',e=>{const b=e.target.closest('[data-decision]');if(!b)return;const action=b.dataset.decision,doi=b.dataset.doi;if(action==='pending'){b.textContent='✓ Kept for review';b.disabled=true;return;}openDecisionDialog(doi,action);});
document.addEventListener('click',e=>{if(e.target.closest('[data-dialog-cancel]')||e.target.classList.contains('decision-confirm-overlay'))closeDecisionDialog();if(e.target.closest('[data-dialog-continue]'))continueDecision();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pendingDecision)closeDecisionDialog();});
async function init(){try{const[rr,dr]=await Promise.all([fetch('./data/academic-review.json',{cache:'no-cache'}),fetch('./data/academic-decisions.json',{cache:'no-cache'})]);if(!rr.ok)throw new Error(`review HTTP ${rr.status}`);const report=await rr.json();if(dr.ok){const data=await dr.json();decisions=new Map((data.decisions||[]).map(d=>[doiNorm(d.doi),d]));}candidates=report.discovered_candidates||[];renderStats(report);render();}catch(error){notice.textContent=`Unable to load review data: ${error.message}`;queue.innerHTML='<div class="review-empty">Review queue unavailable.</div>';}}
if(filter&&!filter.querySelector('[value="needs_review"]'))filter.insertAdjacentHTML('beforeend','<option value="needs_review">Needs review</option><option value="verified">Confirmed mine</option><option value="rejected">Not mine</option>');
search.addEventListener('input',render);filter.addEventListener('change',render);const spotlight=document.getElementById('spotlight');if(spotlight&&!matchMedia('(prefers-reduced-motion: reduce)').matches)addEventListener('pointermove',e=>{spotlight.style.left=`${e.clientX}px`;spotlight.style.top=`${e.clientY}px`},{passive:true});init();
